# Generated by Django 2.2.28 on 2024-03-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200724_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('email', models.CharField(default='', max_length=25)),
                ('password', models.CharField(default='', max_length=100)),
                ('Usergrand', models.CharField(choices=[('Grand', 'Grand'), ('NotGrant', 'NotGrant')], default='NotGrant', max_length=20)),
            ],
        ),
    ]
